### ISSUE TITLE
STR scores

### ISSUE THREAD

**Issue by ltf2020** [fancheyu5/STRAS#1]
hello，I am interested in your tool, can you give a more specific script example

**Comment by fancheyu5** [comment]
> 
Hi,
Snakemake is a pipeline tool, and file named Snakefile is the config file of this pipeline. The first line of Snakefile  defined samplesID as input wildcards.
head -n 1 Snakefile
sample = ["hg002.gangstr"]

If you have set up your conda environment , activated it, and prepared your sample1.bed, sample2.bed file, edit the first line of Snakefile.  Put your sampleIDs in the [] , quot them with "", and seperate by ,
eg. sample=["sample1","sample2"]

Then run this command in terminal
snakemake

I put an example in this file.  As the first line of Snakefile is 
sample = ["hg002.gangstr"]
So if you run         "snakemake"        without editing Snakefile, hg002.gangstr.bed would be  annotated. Annotated tsv and scored tsv would be in results file.

ps. before run a new pipeline, you need to delete results file or rename it.

**Comment by ltf2020** [comment]
i run this command in terminal：snakemake --cores 2.  Would it be possible to provide some support for this issue?
![微信截图_20230220224000](https://user-images.githubusercontent.com/86865694/220136684-fd0a370d-f744-4c7d-8aeb-2f7fe8bb7087.png)

**Comment by fancheyu5** [comment]
> i run this command in terminal：snakemake --cores 2. Would it be possible to provide some support for this issue? ![微信截图_20230220224000](https://user-images.githubusercontent.com/86865694/220136684-fd0a370d-f744-4c7d-8aeb-2f7fe8bb7087.png)

This could be dued to the annot_beds were not downloaded properly as git large files.
Please download them from 
 https://pan.baidu.com/s/1MeukqURTHTtZXjsRqd3f2w?pwd=1234 提取码: 1234 (for Chinese) 
or   https://www.mediafire.com/file/fd5z2wusue5olaf/annot_beds.zip/file
Put it in STRAS file and unzip it.

**Comment by ltf2020** [comment]
Thanks! I have one more question. Is the more harmful，the higher the STR score?

**Comment by fancheyu5** [comment]
> 

Yes, the score is a probability of being classified as disease-associated STR. According to my benchmark dataset generated from clinvar, the cutoff is 0.122.
For more details, you can visit https://www.researchsquare.com/article/rs-2263265/v1

**Comment by ltf2020** [comment]
Thank you a lot!
